name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
        version: '7.5.5'
        projectPath: '${{ github.workspace }}'
        args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites" -apiKey=${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
