<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_daikirktu.lt</name>
   <tag></tag>
   <elementGuidId>b8317145-e454-4348-90fd-11b23827a4e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='contact']/div/div/div/div/address/figure[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>figure:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;daikir@ktu.lt&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9b63a9a-4600-4b5d-80bd-cc528dae56a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:daikir@ktu.lt</value>
      <webElementGuid>c8a8d115-f3bc-4807-89dc-5699e5459d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>daikir@ktu.lt</value>
      <webElementGuid>30f61d5b-f6cc-4514-a6fe-f1cb15649f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ts-box mb-0 p-5 ts-mt__n-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/address[1]/figure[2]/a[1]</value>
      <webElementGuid>6cdd8731-79f8-44c2-8bb3-64ec3d576fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contact']/div/div/div/div/address/figure[2]/a</value>
      <webElementGuid>b16a0bdc-24b1-44c1-b62a-2deb2c0ac062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'daikir@ktu.lt')]</value>
      <webElementGuid>f01ed0a1-a070-4ecd-8762-c5e8815b4b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::a[1]</value>
      <webElementGuid>20f89359-1b97-4d7d-8192-260c5842cea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studentų g. 50, Kaunas, Lithuania'])[1]/following::a[1]</value>
      <webElementGuid>238a5750-4664-4554-9ec3-b916c6fe2e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nojbut@ktu.lt'])[1]/preceding::a[1]</value>
      <webElementGuid>5b51ba75-7773-4b31-a45e-2c6e8170d802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2024 QRWeb, All Rights Reserved'])[1]/preceding::a[2]</value>
      <webElementGuid>899f3235-2cad-4bb5-9e9b-b616da6368ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='daikir@ktu.lt']/parent::*</value>
      <webElementGuid>38ff7024-2177-4b2a-bd95-2c671fda1f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:daikir@ktu.lt')]</value>
      <webElementGuid>59b6b850-2e02-460b-a5c9-54102f688fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure[2]/a</value>
      <webElementGuid>7903f8ed-054a-41a9-83f0-c8dc66ac8550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:daikir@ktu.lt' and (text() = 'daikir@ktu.lt' or . = 'daikir@ktu.lt')]</value>
      <webElementGuid>7f88ae80-2471-4896-8a34-4f62f067a1ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
