<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_cfhftujftu5424hkglhulhl21042</name>
   <tag></tag>
   <elementGuidId>0e9d352a-0754-4537-bf91-f9b34207c2f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_content_editorjs_holder']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.codex-editor__redactor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0573c26d-8141-44b1-9573-b007de1b0ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>codex-editor__redactor</value>
      <webElementGuid>6a413e2c-2fd9-4ead-8fc5-a64a2a2b8569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cfhftujftu5424hkglhulhl21042</value>
      <webElementGuid>1855d3f9-5a9e-4c67-bbc0-c8c36c67b81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_content_editorjs_holder&quot;)/div[@class=&quot;codex-editor&quot;]/div[@class=&quot;codex-editor__redactor&quot;]</value>
      <webElementGuid>34c819da-dbae-470f-b916-b35e52ff0045</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_content_editorjs_holder']/div/div</value>
      <webElementGuid>0f630fe3-ce25-4239-8ae6-763a1fdcbc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null'])[1]/following::div[3]</value>
      <webElementGuid>16a800b2-612b-4012-b0a5-75609d1bbc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>14a8b91b-25ba-425c-a366-5b18b4ed58eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'cfhftujftu5424hkglhulhl21042' or . = 'cfhftujftu5424hkglhulhl21042')]</value>
      <webElementGuid>90290cf7-3891-491d-9c11-23340199bf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
