<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email</name>
   <tag></tag>
   <elementGuidId>9f6512ae-441b-4a59-a144-eb4e49b81a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='contact']/div/div/div/div/address/figure[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.font-weight-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Email:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35466816-b767-4e9e-93e1-dbfb9b165ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold</value>
      <webElementGuid>dbaae573-8518-429d-8c3b-42fcfb3c0769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email:</value>
      <webElementGuid>ae34dce7-0803-41c5-96dc-ad83bb93f696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ts-box mb-0 p-5 ts-mt__n-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/address[1]/figure[2]/div[@class=&quot;font-weight-bold&quot;]</value>
      <webElementGuid>ddf8d16c-05e1-41ed-b3c9-a80af4a9994e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contact']/div/div/div/div/address/figure[2]/div</value>
      <webElementGuid>a5ac81aa-189c-4b92-a8b6-ce8240e84e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studentų g. 50, Kaunas, Lithuania'])[1]/following::div[1]</value>
      <webElementGuid>c1146c36-8e5b-4407-aeb3-3310dc1d5d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::div[1]</value>
      <webElementGuid>afc70cdf-13fd-4ee2-b706-6e126efea209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='daikir@ktu.lt'])[1]/preceding::div[1]</value>
      <webElementGuid>467ed9df-c8a6-4dc9-bea2-93920e5e8780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nojbut@ktu.lt'])[1]/preceding::div[1]</value>
      <webElementGuid>ff758ad0-90dc-448e-bcf5-1e678bd6d441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email:']/parent::*</value>
      <webElementGuid>302d2def-552e-4887-b622-173af18e10fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure[2]/div</value>
      <webElementGuid>e29b94f5-f372-4369-b7de-adfd47b02193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email:' or . = 'Email:')]</value>
      <webElementGuid>7cea8b32-dbb0-4f8e-9dda-1402eb53a05b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
