<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add row aboveAdd row belowDelete rowAdd_87bd6f</name>
   <tag></tag>
   <elementGuidId>75d97d74-ffb9-497c-9196-37f6371626ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cdx-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_content_editorjs_holder']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62a5c85c-2d48-431f-a82b-e0dc1a603066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdx-block</value>
      <webElementGuid>eb4126dc-ef3c-4387-aebb-6f99e4f01dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add row aboveAdd row belowDelete rowAdd column to leftAdd column to rightDelete columnhhhhhhhhhhhhhhhh</value>
      <webElementGuid>a65cc5dc-44b0-4ee5-bfd8-acf8aa3968f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_content_editorjs_holder&quot;)/div[@class=&quot;codex-editor&quot;]/div[@class=&quot;codex-editor__redactor&quot;]/div[@class=&quot;ce-block ce-block--focused&quot;]/div[@class=&quot;ce-block__content&quot;]/div[@class=&quot;cdx-block&quot;]</value>
      <webElementGuid>c373c94a-42e9-4b5a-a2c8-e84526198497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_content_editorjs_holder']/div/div/div/div/div</value>
      <webElementGuid>f591e2fd-4d4f-4a11-b329-9526d1bbf8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null'])[1]/following::div[6]</value>
      <webElementGuid>75a7b8a5-4585-4382-8360-9f71a48247d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>ac8413c5-dc4b-4432-848f-f96d473def01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add row aboveAdd row belowDelete rowAdd column to leftAdd column to rightDelete columnhhhhhhhhhhhhhhhh' or . = 'Add row aboveAdd row belowDelete rowAdd column to leftAdd column to rightDelete columnhhhhhhhhhhhhhhhh')]</value>
      <webElementGuid>dfb91399-b4aa-4c0e-81ca-8a5d1315f5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
