<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Anna                                   _6c39b4</name>
   <tag></tag>
   <elementGuidId>ff5e90b2-12e0-4fc9-9dec-5cccd57c5f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='our-team']/div/div[2]/div[5]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Anna Testing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6e15872-7a8b-4b29-996c-5733588748b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>baa4983b-bfe0-440f-aa1a-861c000f4499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Anna
                                    Testing
                                </value>
      <webElementGuid>f0ee3b36-f613-4a7f-9c0c-12a296c30eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-team&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-lg-3&quot;]/div[@class=&quot;card ts-fadeInUp animated&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>6a2f7452-6ad8-456a-b8e9-b68b971a4166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='our-team']/div/div[2]/div[5]/div/div[2]</value>
      <webElementGuid>534cd765-1a0a-4edc-b025-10579870cdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend'])[2]/following::div[4]</value>
      <webElementGuid>dc812092-de49-4b5c-a770-2f7d992d0578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rustam'])[1]/following::div[4]</value>
      <webElementGuid>704cd591-5bf2-42e5-b2f9-a6bea575427b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]</value>
      <webElementGuid>b04e43e4-abf0-46df-ba58-1b851d866934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                    Anna
                                    Testing
                                ' or . = '
                                    Anna
                                    Testing
                                ')]</value>
      <webElementGuid>c8772f32-2fe1-454f-90e1-faeed8d5799b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
