<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_19,99</name>
   <tag></tag>
   <elementGuidId>6eb2efae-69c4-4fd4-84c8-68571aa1c7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='pricing']/div/div[2]/div[3]/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;$19,99&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>741f85d9-cd88-4c67-a100-5794513695c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 font-weight-normal</value>
      <webElementGuid>06eace6f-455d-4f21-96c3-109e50a97a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            $19,99
                                        </value>
      <webElementGuid>bcd22943-4efb-4ae0-8aff-74d100682976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pricing&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row no-gutters ts-cards-same-height&quot;]/div[@class=&quot;col-sm-4 col-lg-4&quot;]/div[@class=&quot;card text-center ts-price-box ts-fadeInUp animated&quot;]/div[@class=&quot;card-header p-0&quot;]/div[@class=&quot;ts-title py-5 mb-0&quot;]/h3[@class=&quot;mb-0 font-weight-normal&quot;]</value>
      <webElementGuid>ccc20dc6-a493-4611-8acc-40cc69f89784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='pricing']/div/div[2]/div[3]/div/div/div/h3</value>
      <webElementGuid>bafe9e75-3143-4587-80c6-e910b97deac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium'])[2]/following::h3[1]</value>
      <webElementGuid>f9118d61-b229-4db7-adff-62037d88de80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ads Removed'])[2]/following::h3[1]</value>
      <webElementGuid>0aac42bd-d473-4b16-a1a1-24602bcad83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='per month'])[2]/preceding::h3[1]</value>
      <webElementGuid>a81a5022-f152-483a-82d0-fc1bde164244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19,99']/parent::*</value>
      <webElementGuid>d551f56f-3870-4f58-bb83-1810e92cf826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/h3</value>
      <webElementGuid>86512984-4dea-4303-b34f-3103b9901eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = '
                                            $19,99
                                        ' or . = '
                                            $19,99
                                        ')]</value>
      <webElementGuid>fbe1066e-b39e-43b2-8461-92eeba49baa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
