<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Free</name>
   <tag></tag>
   <elementGuidId>952c5908-5b2a-4cbf-b642-1ad51187967d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='pricing']/div/div[2]/div/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.mb-0.font-weight-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Free&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>e535909a-29ca-44ff-be16-f51de2ec071d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 font-weight-normal</value>
      <webElementGuid>699ea63d-1a92-460b-b2bd-121c4ff408e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Free</value>
      <webElementGuid>15c25002-f977-4840-a3ea-8d34f2d6957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pricing&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row no-gutters ts-cards-same-height&quot;]/div[@class=&quot;col-sm-4 col-lg-4&quot;]/div[@class=&quot;card text-center ts-price-box ts-fadeInUp animated&quot;]/div[@class=&quot;card-header p-0&quot;]/div[@class=&quot;ts-title py-5 mb-0&quot;]/h3[@class=&quot;mb-0 font-weight-normal&quot;]</value>
      <webElementGuid>801b9b5b-5525-4d9d-98d1-a812a81e6972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='pricing']/div/div[2]/div/div/div/div/h3</value>
      <webElementGuid>ff217112-ea3f-4fbe-ab04-880c7599e7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/following::h3[1]</value>
      <webElementGuid>358096b8-24d8-479a-ac72-4d29ffabeeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affordable Prices'])[1]/following::h3[1]</value>
      <webElementGuid>e4860281-df75-44dc-9b56-d107c6e1eb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='forever'])[1]/preceding::h3[1]</value>
      <webElementGuid>9dc9ef1d-1ba9-4bd3-8d15-286023f89ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Backup'])[1]/preceding::h3[1]</value>
      <webElementGuid>a410137b-217d-47c5-b01e-8e5293cad1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Free']/parent::*</value>
      <webElementGuid>1a34c08a-4b15-4564-9c25-fd9e395fedca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/h3</value>
      <webElementGuid>39bbc2f0-7792-4d6e-9bfb-ac0cac562274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Free' or . = 'Free')]</value>
      <webElementGuid>b69431de-91e8-457d-a715-4759fa6716be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
