<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Anna</name>
   <tag></tag>
   <elementGuidId>4bf1fcec-7fe6-47bc-a08c-4aa8f83b6a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='our-team']/div/div[2]/div[5]/div/div[2]/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Anna&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>a89cdb9a-9a1c-4de1-b741-31867db78fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>54212178-5303-4439-a2ba-ce8c863955d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anna</value>
      <webElementGuid>ade2f42c-74a6-4b5d-9e11-d5c33c962015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-team&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-lg-3&quot;]/div[@class=&quot;card ts-fadeInUp animated&quot;]/div[@class=&quot;card-body&quot;]/h5[@class=&quot;mb-1&quot;]</value>
      <webElementGuid>3c3d43bd-a838-4f60-8819-75572be01160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='our-team']/div/div[2]/div[5]/div/div[2]/h5</value>
      <webElementGuid>fbf691e3-64ba-42a4-a895-7b2d530ae780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend'])[2]/following::h5[1]</value>
      <webElementGuid>c69d3585-36fe-4c8e-810b-1d6c44be7ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rustam'])[1]/following::h5[1]</value>
      <webElementGuid>c5a3f44a-44ac-4797-bec2-66adc205a227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/preceding::h5[1]</value>
      <webElementGuid>51feb583-f747-4758-9d85-0f18e355d5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::h5[1]</value>
      <webElementGuid>f0aaa5a3-6d4e-42fe-bc73-10f2323a412a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anna']/parent::*</value>
      <webElementGuid>897163f1-5aea-4c7c-b712-cd74d3c9bfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/h5</value>
      <webElementGuid>2b6e80c9-f382-4fe9-977e-72b3ebbb2f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Anna' or . = 'Anna')]</value>
      <webElementGuid>8a62ed28-f942-40be-bbf0-9d9bd340ffb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
