<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Backend</name>
   <tag></tag>
   <elementGuidId>7cc810fc-0821-4330-ae19-f25cdb7704a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='our-team']/div/div[2]/div[3]/div/div[2]/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Backend&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>17db389a-f9b7-45ab-80b8-5f23830c2af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ts-opacity__50</value>
      <webElementGuid>67ab26f6-7516-44c5-b40b-cce4f859e542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backend</value>
      <webElementGuid>3f9a536f-461e-4be6-beb3-d70057f247fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-team&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-lg-3&quot;]/div[@class=&quot;card ts-fadeInUp animated&quot;]/div[@class=&quot;card-body&quot;]/h6[@class=&quot;ts-opacity__50&quot;]</value>
      <webElementGuid>82c76372-42f2-4b72-8985-44d1cdf5b065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='our-team']/div/div[2]/div[3]/div/div[2]/h6</value>
      <webElementGuid>80abbd7c-065e-4ebc-982c-b0e7d043f1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vlad'])[1]/following::h6[1]</value>
      <webElementGuid>f5557f9f-6d21-4cd5-b998-8bbde87171ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontend'])[1]/following::h6[1]</value>
      <webElementGuid>eace4d51-b92c-4a43-b8d3-94763ea2ee73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rustam'])[1]/preceding::h6[1]</value>
      <webElementGuid>6a23d84b-7720-4317-b830-658c7666fc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend'])[2]/preceding::h6[1]</value>
      <webElementGuid>6df4eaca-9fe9-4a82-b730-7a5b55066a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Backend']/parent::*</value>
      <webElementGuid>dfa18adf-cc11-42a9-85f9-19bebf4159cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/h6</value>
      <webElementGuid>031e99bf-26d8-45a0-a2da-5627830f2733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Backend' or . = 'Backend')]</value>
      <webElementGuid>13dcd039-38f3-4a2d-84e8-c364be8db810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
