<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Convenient</name>
   <tag></tag>
   <elementGuidId>a1cfd404-fb81-4f40-86ad-e24e86497b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='features']/div/div/div[2]/ul/li[3]/a/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.ts-font-color__black > h6.my-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Convenient&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>e4ed32ce-cf03-4f20-9e11-a5c454e4691d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-2</value>
      <webElementGuid>1d5a1012-8dc5-465f-bbf5-e11504d70f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Convenient</value>
      <webElementGuid>079de215-4752-4dd5-aeed-915feb319626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;features&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 col-xl-5 ts-fadeInUp animated&quot;]/ul[@class=&quot;list-unstyled ts-list-divided&quot;]/li[3]/a[@class=&quot;ts-font-color__black&quot;]/h6[@class=&quot;my-2&quot;]</value>
      <webElementGuid>e3d5de3e-d659-4421-8fc8-5d5dc5ef6acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='features']/div/div/div[2]/ul/li[3]/a/h6</value>
      <webElementGuid>b92eface-9a83-47dd-ade1-f062ef233b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fast'])[1]/following::h6[1]</value>
      <webElementGuid>6837c2c6-654f-4b10-8bd6-c878e5606d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple To Use'])[1]/following::h6[2]</value>
      <webElementGuid>0736285e-bdc0-4272-95b0-e719f3178c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affordable Prices'])[1]/preceding::h6[1]</value>
      <webElementGuid>c8349480-0e9f-4e50-baef-43de617450c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/preceding::h6[1]</value>
      <webElementGuid>e222ca1b-8313-4843-9e7a-b1bb5dfdfe83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Convenient']/parent::*</value>
      <webElementGuid>44712716-4486-49b0-b594-458c7cec6cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/h6</value>
      <webElementGuid>eb4084ca-3ed1-4aa3-bcda-374c20019d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Convenient' or . = 'Convenient')]</value>
      <webElementGuid>f71b9882-35ee-4aa7-a34f-1462f9b91de8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
