<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Simple To Use</name>
   <tag></tag>
   <elementGuidId>f627f5c6-5300-40f0-a7ad-e067cc390f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.my-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='features']/div/div/div[2]/ul/li/a/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Simple To Use&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>72edf826-82b9-47f3-88e3-6368ab704ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-2</value>
      <webElementGuid>a6d5cdbc-9b50-48f8-a3c6-702da0b92b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simple To Use</value>
      <webElementGuid>a6406eb2-82df-443c-a963-af1b56590f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;features&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 col-xl-5 ts-fadeInUp animated&quot;]/ul[@class=&quot;list-unstyled ts-list-divided&quot;]/li[1]/a[@class=&quot;ts-font-color__black&quot;]/h6[@class=&quot;my-2&quot;]</value>
      <webElementGuid>c70ed303-4bf4-4fe3-a9f2-2e2d70147c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='features']/div/div/div[2]/ul/li/a/h6</value>
      <webElementGuid>0b56a8b5-9620-417a-b685-338a51c01d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::h6[1]</value>
      <webElementGuid>311dd91a-76a3-4d27-9b7b-109c7f339489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up Now!'])[1]/following::h6[1]</value>
      <webElementGuid>b8f9b7e9-b6bc-4fe6-8e42-dcc447be31c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fast'])[1]/preceding::h6[1]</value>
      <webElementGuid>31aa2753-d204-47a0-a1a8-5522ad5f904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convenient'])[1]/preceding::h6[2]</value>
      <webElementGuid>bc949f40-b276-4ede-8bc5-1628b114ed39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simple To Use']/parent::*</value>
      <webElementGuid>548ab99c-07c8-4a99-881b-8421a0035eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>14355053-404e-4774-98e0-5e6ba6abeb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Simple To Use' or . = 'Simple To Use')]</value>
      <webElementGuid>09cd08eb-e7e7-41c3-aa41-b8d2e23e5410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Now!'])[1]/following::h6[1]</value>
      <webElementGuid>f973a1d5-7d1b-400e-a956-73f9d5aa1625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
