<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c4815659-b79b-48a0-854b-445a19afe00e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.navbar-brand</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2da16d33-3872-4f0a-9c93-91902722166b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>static/assets/img/logo-w.png</value>
      <webElementGuid>93de50f3-9c14-49ad-9025-40c2603132d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;has-loading-screen loading-done&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-dark fixed-top ts-separate-bg-element&quot;]/div[@class=&quot;container&quot;]/a[@class=&quot;navbar-brand&quot;]/img[1]</value>
      <webElementGuid>fa1b140d-6fbe-40e3-a61d-e4ab11588fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>235e7a53-305d-4ca2-86f8-03b8a05d5f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'static/assets/img/logo-w.png']</value>
      <webElementGuid>18023cf0-60b9-4620-bc70-f9e5ced0190f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
