<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>0c7bd376-3a4c-4041-9c1e-68ed18eceb82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='how-it-works']/div/div[2]/div/figure/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>figure.icon.mb-5.p-2 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>figure >> internal:has-text=&quot;Create Your Page Morbi et nisl a sapien malesuada scelerisque. Suspendisse tempo&quot;i >> img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c66575a4-f771-404f-b653-9b6bc64b64fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>static/assets/img/page-creation.jpg</value>
      <webElementGuid>c4d8797d-99b0-4d5c-9f63-1116cad90816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;how-it-works&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-4 col-xl-4&quot;]/figure[@class=&quot;ts-fadeInUp animated&quot;]/figure[@class=&quot;icon mb-5 p-2&quot;]/img[1]</value>
      <webElementGuid>68646056-76a1-49ce-aa8e-d867815da814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='how-it-works']/div/div[2]/div/figure/figure/img</value>
      <webElementGuid>e7f8fcac-fcdc-4983-bdd7-3c29d7e75d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>ee4d9c7c-e9a8-4299-9ccd-c6edc3dd650e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'static/assets/img/page-creation.jpg']</value>
      <webElementGuid>fca933ca-b816-4b88-8b58-3b72b1371d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
