<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3</name>
   <tag></tag>
   <elementGuidId>f44e115c-3427-490e-bce8-5f3f4ec92b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='how-it-works']/div/div[2]/div[3]/figure/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.offset-sm-4.col-md-4.offset-md-0.col-xl-4 > figure.ts-fadeInUp.animated > figure.icon.mb-5.p-2 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>figure >> internal:has-text=&quot;Share It In non turpis convallis nunc fermentum porttitor sed quis sapien. Etiam&quot;i >> img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1bc686ce-c8c8-4b07-b080-2825fefae166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>static/assets/img/share-it.jpg</value>
      <webElementGuid>36236e7d-c8d3-4dc3-99b8-432063eeae49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;how-it-works&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 offset-sm-4 col-md-4 offset-md-0 col-xl-4&quot;]/figure[@class=&quot;ts-fadeInUp animated&quot;]/figure[@class=&quot;icon mb-5 p-2&quot;]/img[1]</value>
      <webElementGuid>1a169d57-44e1-4c56-8d5c-9bbb81ab0305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='how-it-works']/div/div[2]/div[3]/figure/figure/img</value>
      <webElementGuid>095c23f8-d252-46b5-8130-724521073e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/figure/figure/img</value>
      <webElementGuid>48236035-acc0-4815-b7a3-ea79e04daf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'static/assets/img/share-it.jpg']</value>
      <webElementGuid>ab85e666-b913-4193-8e5c-95b06d14eebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
