<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>4ec06806-f82c-4fe3-8686-0129be4f0eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='how-it-works']/div/div[2]/div[2]/figure/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>figure >> internal:has-text=&quot;Link It To QR Curabitur tellus enim, aliquet et porttitor id, accumsan at nulla.&quot;i >> img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e37f659e-6072-48cb-b9e3-44b68b751b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>static/assets/img/qr-code.png</value>
      <webElementGuid>78338346-1fae-445b-91d9-d2d7d8cdebbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>7b3f819e-4553-496b-9650-c1091fd23ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;how-it-works&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-4 col-xl-4&quot;]/figure[@class=&quot;ts-fadeInUp animated&quot;]/figure[@class=&quot;icon mb-5 p-2&quot;]/img[1]</value>
      <webElementGuid>2593cbd5-a2a8-4880-9760-2307f7e879f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='how-it-works']/div/div[2]/div[2]/figure/figure/img</value>
      <webElementGuid>bdb2da4b-fffc-47fe-881c-52932f99b6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/figure/figure/img</value>
      <webElementGuid>17673352-a2b4-4d8f-a126-3200d511956c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'static/assets/img/qr-code.png']</value>
      <webElementGuid>165f7d01-6970-4da4-a958-9ab93cf19fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
