<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_5424</name>
   <tag></tag>
   <elementGuidId>4477539f-2f3a-4ed3-9a0c-9562959a39f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id_content_editorjs_holder']/div/div/div[2]/div/ol/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.cdx-list__item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>eb51a728-8f43-4301-a022-5869debbec11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdx-list__item</value>
      <webElementGuid>06fff865-b869-4313-b21d-708ad0fab591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5424</value>
      <webElementGuid>fc3a243c-5a5e-4409-8502-879e11ae26d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_content_editorjs_holder&quot;)/div[@class=&quot;codex-editor&quot;]/div[@class=&quot;codex-editor__redactor&quot;]/div[@class=&quot;ce-block ce-block--focused&quot;]/div[@class=&quot;ce-block__content&quot;]/ol[@class=&quot;cdx-block cdx-list cdx-list--ordered&quot;]/li[@class=&quot;cdx-list__item&quot;]</value>
      <webElementGuid>3b41b0ae-794e-454f-bb7b-120529d89098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id_content_editorjs_holder']/div/div/div[2]/div/ol/li</value>
      <webElementGuid>ade38d55-704e-4423-9fdc-1d53599ea91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cfhftujftu'])[1]/following::li[1]</value>
      <webElementGuid>a56cf61a-484e-4530-9c47-f11a661b751f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null'])[1]/following::li[1]</value>
      <webElementGuid>44afef4d-9edc-4638-a54f-542ebbe6035b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing found'])[1]/preceding::li[1]</value>
      <webElementGuid>4ade2a79-7ba6-4c09-9474-992d489963cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text'])[1]/preceding::li[1]</value>
      <webElementGuid>8628b1cd-bd41-4f44-9d31-d363f77831f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5424']/parent::*</value>
      <webElementGuid>c2c4569a-c5d8-4001-b571-48a37562f2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>72a4d41a-dc1f-47c9-938f-81d60b1c409a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '5424' or . = '5424')]</value>
      <webElementGuid>ba6cb3cb-41f6-4412-849d-fd66143b4d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
