name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Simple Test Suite Collection" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
    - name: Katalon Report Uploader
      uses: katalon-studio/report-uploader@v0.0.8
      env:
          PASSWORD: ae02f853-776e-4c54-905d-d67f8fb32c85
          PROJECT_ID: 1432391
          TYPE: katalon
          REPORT_PATH: reports
