name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Katalon Studio
      uses: katalon-studio/katalon-studio-github-action@v3.0
    - name: Katalon Report Uploader
      uses: katalon-studio/report-uploader@v0.0.8
      env:
          PASSWORD: ae02f853-776e-4c54-905d-d67f8fb32c85
          PROJECT_ID: 1432391
          TYPE: katalon
          REPORT_PATH: reports
