name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipo
        pip install -r requirements.txt
        pip install pylint==2.3.0
        pip install pylint-django==2.3.0
    - name: Analysing the code with pylint
      run: |
        pylint -j 0\
              --load-plugins=pylint_django \
              --max-parents='14' \
              --django-settings-module=qr_web.settings \
              $(git ls-files '*.py')
