name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pylint-django
    - name: Load environment variables from .env
      run: |
        if [ -f .env ]; then
          export $(cat .env | grep -v ^# | xargs)
        fi
    - name: Set Django settings module
      run: echo "DJANGO_SETTINGS_MODULE=qr_web.settings" >> $GITHUB_ENV
    - name: Analysing the code with pylint (all files except settings.py)
      run: |
        pylint -j 0 \
               --load-plugins=pylint_django \
               --django-settings-module=qr_web.settings \
               --max-parents='14' \
               $(git ls-files '*.py')
